server:
  port: 8081

spring:
  application:
    name: provider-api-openapi

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs

logging:
  level:
    root: INFO
    edu.course.provider: DEBUG

